### PR TITLE
Integrate cvat infrastructure into Weed-AI docker compose

### PR DESCRIPTION
**Pull request by ElevnLi**
Clone from my forked version https://github.com/Weed-AI/cvat/tree/usyd
Build cvat-ui using `docker-compose build --no-cache cvat_ui`
Run `COMPOSE_HTTP_TIMEOUT=500 docker-compose -f docker-compose-dev.yml up` to start Weed-AI
Go to localhost/cvat-annotation to use cvat

### CODE REVIEW

**Comment by jnothman** [comment]
Please check if the readme needs updating

**Review by jnothman — APPROVED** [review]
Okay. I wonder if the CVAT build stuff should be up the top

**Comment by ElevnLi** [comment]
> Okay. I wonder if the CVAT build stuff should be up the top

Yeah that is much better for quick setup and testing.
Do we have to include cvat as a sub dir instead of a sub module to achieve that?

**Comment by jnothman** [comment]
> Do we have to include cvat as a sub dir instead of a sub module to achieve that?

I'm not sure why we'd need to?

**Comment by jnothman** [comment]
Now working on branch with git submodule

**Pull request closed without merging**
