### PR TITLE
modernise UI for selecting annotation type

### PR DESCRIPTION
**Pull request by jnothman**
Just because I felt like it, and thought it would simplify handling annotation type in Update functionality (#592), I decided to rewrite the UI for selecting annotation type:

ezgif com-gif-maker (3)

(I've made the Next button work since taking that video)

### CODE REVIEW

**Comment by jnothman** [comment]
If we integrate this into the Update feature, we could have Edit default to COCO and start displaying the COCO Upload step immediately (not select annotation format).

It would also be nice if the step navigation up top was able to be clicked if all preceding steps are valid.

**Review by ElevnLi — APPROVED** [review]
LGTM
I learned a lot from this pr. Thanks!

**Comment by jnothman** [comment]
Thanks for helping me lint!

**Comment by jnothman** [comment]
And you're right, it's a nice, clean PR that separates the generic from the application code and removes some unneeded coupling.

**Pull request merged**
