### PR TITLE
Cvat uploader cypress

### PR DESCRIPTION
**Pull request by ElevnLi**
Resolves https://github.com/Weed-AI/annotation-platform/issues/28

### CODE REVIEW

**Comment by jnothman** [comment]
the docker-compose here requires pre-building an image. Rather, we should merge in the [submodule branch](https://github.com/Weed-AI/Weed-AI/tree/cvat-uploader-as-submodule)

**Comment by ElevnLi** [comment]
That branch is still using original image. All these changes of cvat and cypress are only on dev. Will move to prod when it's working

**Comment by jnothman** [comment]
It's fine to update the commit ref in the submodule branch. OTOH, @spikelynch hasn't updated `.github/workflows/frontend.yml` to use the submodule, and we should open a PR to test it separately.

**Comment by spikelynch** [comment]
I'll update the workflows on the submodule branch.

**Comment by ElevnLi** [comment]
closed by #612

**Pull request closed without merging**
